# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
    retry:
      manual:
        permit_on_passed: true
  plugins:
    ecr: &ecr
      ecr#v2.0.0:
        login: true
        no-include-email: true
steps:
  - label: ":git: Deploy"
    <<: *step-defaults
    concurrency: 1
    concurrency_group: '$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BRANCH/deploy'
    branches:
      - main
      - develop
      - uat-forumone
      - buildkite
    plugins:
      # Log into ECR for this build step to access and push images.
      - *ecr

      # Download the prebuilt image and extract project files to the
      # local filesystem for further operations.
      - forumone/extract#v0.2.0:
          image: ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}
          from: /app
          to: ${ARTIFACT_LOCATION}/client

      # Execute an artifact deployment using the defined branch to
      # environment mapping.
      - forumone/artifact-push#v0.3.1:
          verbose: true
          source-directory: ${ARTIFACT_LOCATION}
          remote: oafzps2pqxjxw@git.us-2.platform.sh:oafzps2pqxjxw.git
          branches:
            # - match: develop
            #   target: main
            - match: buildkite
              target: main
#            - match: main
#              target: main
          ssh:
            keyscan: git.us-2.platform.sh
          git:
            name: F1 Builder
            email: support+f1builder@forumone.com

          files:
            force-add:
              - client/node_modules
              - client/_site
            ignore:
              - .git/
              - .gitignore
              - .lando.yml
              - .platform/
              - .platform.drupal.yml
              - Dockerfile
              - README.md
              - api/
              - header.svg
              - client/.gitignore
              - client/.platform.app.yaml
              - client/.lando.upstream.yml
              - client/.env.example
              - client/get_local_config.sh
              - client/platformsh-scripts/
