name: Deploy to staging environment - stg-www.foia.gov
on:
  push:
    branches:
      - release*
jobs:
  # Build for the Acquia Cloud Staging environment
  build:
    env:
      GIT_REPO: ${{ secrets.GIT_REPO }}
      APP_ENV: staging
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        name: Setup RUBY
      - name: Install dependencies
        run: |
          npm i
          bundle install
      - name: Run build
        run: |
          NODE_ENV=production make build
      # Install SSH Key
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Acquia known hosts
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - name: Deploy to Acquia development
        run: |
          chmod +x ./bin/git-deploy.sh
          ./bin/git-deploy.sh _site staging
        shell: bash
